{% set version = 'internal_' + DATE %}

about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The main Gemini Python package for processing data
build:
    binary_relocation: True
    number: '0'
    script: python setup.py install
package:
    name: gemini.gemini_python
    version: {{ version }}
source:
    fn: gemini_python-{{ version }}.tar.gz
    url: http://astroconda-source:4440/gemini_python-{{ version }}.tar.gz
requirements:
    # Most of the dependencies besides python are not actually needed to
    # "build" gemini_python, but including them here ensures that they get
    # built and therefore that the package is installable.
    build:
    - python x.x                # syntax needed to force 2.7 builds...
    - astropy >=1.0.1
    - beautifulsoup4 >=4.0      # internal-only AstroData doc generation
    - future >=0.15
    - tk >=8.5
    - matplotlib >=1.4.2
    - nose >=1.1.2
    - numpy >=1.9.1
    - pyds9 >=1.8.1
    - pyraf >=2.1.6
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - sphinx >=1.2.2
    - sqlalchemy >=1.0
    - stsci.convolve >=2.1.3
    - stsci.numdisplay >=1.6
    - sextractor >=2.8.6
    run:
    - python >=2.7,<3.0
    - astropy >=1.0.1
    - future >=0.15
    - tk >=8.5
    - matplotlib >=1.4.2
    - nose >=1.1.2
    - numpy >=1.9.1
    - pyds9 >=1.8.1
    - pyraf >=2.1.6
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - sphinx >=1.2.2
    - sqlalchemy >=1.0
    - stsci.convolve >=2.1.3    # Ureka's 2.2.0 not avl in astroconda?
    - stsci.numdisplay >=1.6
    - sextractor >=2.8.6
    # Optional:
    # - guppy (devel/examples)
    # - memory_profiler (devel/primitivesRefactor)
    # - pydot (typelib.py)
    # - pysao (nici)

