build:
    binary_relocation: True
    number: '0'
    script: $PYTHON setup.py install
package:
    name: gemaux_python
    version: "2.1.1"
source:
    git_url: git@gitlab.gemini.edu:DRSoftware/gemaux_python.git
    git_tag: v2.1.1
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The "gemaux" Python package, for internal Gemini operations
requirements:
    # Most of the dependencies besides python are not actually needed to
    # "build" gemaux_python, but including them here ensures that they get
    # built and therefore that the package is installable.
    build:
    - python
    - astropy >=2
    - dragons >=2.1.1
    - matplotlib >=1.4.2
    - numpy >=1.9.1
    - pyds9 >=1.8.1
    - pyraf >=2.1.6
    - python-dateutil >=2.5.3
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    # Several of these modules are only used in one or two scripts, but all
    # except pyds9 are already indirect dependencies via dragons anyway.
    run:
    - python
    - astropy >=2                    # just cleanir.py
    - dragons >=2.1.1
    - matplotlib >=1.4.2             # just cleanir.py
    - numpy >=1.9.1
    - pyds9 >=1.8.1                  # just gsfpos/goipos
    - pyraf >=2.1.6                  # just cleanir.py
    - python-dateutil >=2.5.3        
    - scipy >=0.15.1                 # just cleanir.py & create_illum_mask.py
    - scikit-image >=0.10.1          # just create_illum_mask.py
