{% set version = '3.1.0' %}
{% set tag = 'v' + version %}
{% set number = '0' %}

package:
    name: gemaux_python
    version: {{ version }}
source:
    git_url: git@gitlab.gemini.edu:DRSoftware/gemaux_python.git
    git_tag: {{ tag }}
build:
    binary_relocation: True
    number: {{ number }}
    noarch: python
    script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vv
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The "gemaux" Python package, for internal Gemini operations
requirements:
    build:
    - python
    - pip
    - setuptools
    run:
    - python
    - astropy >=4.3,!=5.3.0          # for AstroData, as in dragons
    - dragons >=3.1.0
    - future >=0.17                  # just redux_utils
    - imexam >=0.8                   # goipos/gsfpos, replacing pyds9
    - matplotlib >=3.1               # just cleanir.py, calculate_gmos_qe.py
    - numpy >=1.19                   # earlier vers prob. OK but not re-tested
  # - pyraf >=2.2.1                  # just cleanir.py; avoid IRAF dep on Py 3
    - python-dateutil >=2.5.3
    - requests >=2.23                # just archive_access & fire
    - scikit-image >=0.10.1          # just create_illum_mask.py
    - scipy >=1.3
    - urllib3 >=2.0                  # just scales
