build:
    binary_relocation: True
    number: '0'
    script: $PYTHON setup.py install
package:
    name: dragons
    version: "3.1.0.dev"
source:
    git_url: git@github.com:GeminiDRSoftware/DRAGONS.git
    git_tag: v3.1.0-dev
about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The main DRAGONS package for processing Gemini data
requirements:
    # Most of the dependencies besides python are not actually needed to
    # "build" dragons, but including them here ensures that they get built
    # and therefore that the package is installable.
    build:
    - python
    - setuptools
    - asdf >=2.7,!=2.10.0
    - astropy >=4.3
    - astroquery >=0.4
    - astroscrappy >=1.1
    - bokeh >=2.3
    - bottleneck >=1.2
    - cython >=0.29
    - docutils >=0.15
    - fitsverify >=4.17
    - future >=0.17
    - gwcs >=0.15
    - holoviews >=1.14
    - imexam >=0.8
    - jinja2 >=3.0
    - jsonschema >=3.0
    - matplotlib >=3.1
    - numpy >=1.17
    - psutil >=5.6
    - pyerfa >=1.7
  # - pytest >=5.2
    - python-dateutil >=2.5.3
    - requests >=2.22
    - scipy >=1.3
    - sextractor >=2.8.6
    - specutils >=1.1,<1.9  # [py<38]
    - specutils >=1.1       # [py>=38]
    - sphinx >=1.2.2
    - sphinx_rtd_theme >=0.3.0
    - sqlalchemy >=1.3,<2.0.0a0
    - tornado >=5.1
    run:
    - python
    - asdf >=2.7,!=2.10.0
    - astropy >=4.3
    - astroquery >=0.4
    - astroscrappy >=1.1
    - bokeh >=2.3
    - bottleneck >=1.2          # opt but needed for astropy.stats performance
    - fitsverify >=4.17
    - future >=0.17
    - gemini_calmgr >=1.1
    - gemini_obs_db >=1.0
    - gwcs >=0.15
    - holoviews >=1.14
    - imexam >=0.8              # optional for SQ (used by gemaux & debug plots)
    - jinja2 >=3.0
    - jsonschema >=3.0
    - matplotlib >=3.1
    - numpy >=1.17
    - psutil >=5.6
    - pyerfa >=1.7
  # - pytest >=5.2              # also need pytest_dragons etc. for self test
    - python-dateutil >=2.5.3
    - requests >=2.22
    - scipy >=1.3
    - sextractor >=2.8.6
    - specutils >=1.1,<1.9  # [py<38]
    - specutils >=1.1       # [py>=38]
    - sqlalchemy >=1.3,<2.0.0a0  # new v2 API breaks calmgr
    - tornado >=5.1
    run_constrained:
    - ds9 >=8.0
