{% set version = tag + '_' + DATE %}

about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The main DRAGONS package for processing Gemini data
build:
    binary_relocation: True
    number: '0'
    script: $PYTHON setup.py install
package:
    name: dragons
    version: {{ version }}
source:
    fn: DRAGONS-{{ version }}.tar.gz
    url: http://astroconda-source:4440/DRAGONS-{{ version }}.tar.gz
requirements:
    # Most of the dependencies besides python are not actually needed to
    # "build" dragons, but including them here ensures that they get built
    # and therefore that the package is installable.
    build:
    - python
    - astropy >=1.2.1
    - cython >=0.24.1
    - future >=0.16.0
    - matplotlib >=1.4.2
    - numpy >=1.9.1
    - pyraf >=2.1.6
    - pytest >=2.9.2
    - python-dateutil >=2.5.3
    - requests >=2.11.1
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - sphinx >=1.2.2
    - sqlalchemy >=1.0
    - stsci.numdisplay >=1.6
    - fitsverify >=4.17
    - sextractor >=2.8.6
    run:
    - python
    - astropy >=1.2.1
    - future >=0.16.0
    - matplotlib >=1.4.2
    - numpy >=1.9.1
    - pyraf >=2.1.6
    - pytest >=2.9.2
    - python-dateutil >=2.5.3
    - requests >=2.11.1
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - sphinx >=1.2.2
    - sqlalchemy >=1.0
    - stsci.numdisplay >=1.6
    - fitsverify >=4.17
    - sextractor >=2.8.6
