# This meta-package (roughly equivalent to "anaconda iraf-all pyraf stsci") is
# used for configuration control of the base Anaconda & AstroConda package
# versions used internally at Gemini.
#
# - The "gemini-anaconda" package is almost the same as "anaconda" in the root
#   environment, but potentially with minor edits to allow for specific version
#   requirements or conflicts.
# - The "stsci" meta-package and its sub-packages do not pin dependencies to
#   specific versions, so are recreated here; likewise for iraf-all.
# - Using OS-specific "builds" allows for unavailability of particular packages
#   on a certain OS or Python version.

build:
    number: '0'
package:
    name: gemini-base
    version: 4.0
about:
    license: BSD
    summary: Base AstroConda installation for internal use at Gemini
requirements:
    # There are no build requirements since we don't maintain the packages
    # (and if we were to, it wouldn't be via this particular meta-package).
    build:
    - python  # needs to be in the recipe for Python-specific builds
    run:
    - python
    - gemini-anaconda ==2019.10.g0  # [py2k]
    - gemini-anaconda ==2020.11.g0  # [py3k]
    # -----
    - iraf ==2.16.UR    # [py2k]
    - iraf ==2.16.UR.1  # [py3k]
    - iraf-x11 ==2.0
    - iraf.adccdrom ==2013_01_02
    - iraf.axe ==2.6.2
    - iraf.cfh12k ==2013_01_02
    - iraf.cirred ==2007_12_13
    - iraf.ctio ==2010_11_18
    - iraf.cutoutpkg ==2001_04_05
    - iraf.deitab ==2013_01_02
    - iraf.esowfi ==2013_01_02
    - iraf.finder ==2.2
    - iraf.fitsutil ==2011_02_22
    - iraf.gmisc ==2010_11_18
    - iraf.guiapps ==2010_11_18
    - iraf.mem0 ==2013_01_02
    - iraf.mscdb ==2011_02_28
    - iraf.mscred ==5.04
    - iraf.mtools ==2013_01_02
    - iraf.nfextern ==2013_01_02
    - iraf.rvsao ==2.7.8
    - iraf.sqiid ==2013_01_02
    - iraf.stecf ==3.17
    - iraf.stsdas ==3.18.3
    - iraf.tables ==3.18.3
    - iraf.ucsclris ==2013_01_02
    - iraf.upsqiid ==2013_01_02
    - iraf.xdimsum ==2010_11_18
    - iraf.xray ==2.5.y2k
    # -----
    - pyraf ==2.1.15
    - pyraf.kepler ==2.6.3  # [py2k]
    # -----
    - acstools ==2.1.0  # [py2k]
    - acstools ==3.3.1  # [py3k]
    - asdf ==1.3.3  # [py2k]
    - asdf ==2.7.1  # [py3k]
    - asteval ==0.9.13
    - astroimtools ==0.1.1  # [py2k]
    - astroimtools ==0.3  # [py3k]
    - astroquery ==0.3.9  # [py2k]
    - astroquery ==0.4  # [py3k]
    - atlas-generic ==3.10.2  # [linux]
    - calcos ==3.3.5  # [py2k]
    - calcos ==3.3.9  # [py3k]
    - cfitsio ==3.470
    - costools ==1.2.3
    - crds ==7.2.4  # [py2k]
    - crds ==10.3.0  # [py3k]
    - cubeviz ==0.2.1  # [py2k]
    - cubeviz ==0.3.0  # [py3k]
    - d2to1 ==0.2.12.post1
    - da5-notebooks ==1.0  # [py3k]
    - dbus-glib ==0.108  # [py2k and linux]
    - dbus-python ==1.2.4  # [py2k and linux]
    - dill ==0.3.2  # [py2k]
    - dill ==0.3.3  # [py3k]
    - docopt ==0.6.2  # [py2k]
    - drizzlepac ==2.2.6  # [py2k]
    - drizzlepac ==3.1.8  # [py3k]
    - ds9 ==8.0.1  # [py2k]
    - ds9 ==8.1  # [py3k]
    - fast-histogram ==0.7  # [py2k]
    - fast-histogram ==0.9  # [py3k]
    - fftw ==3.3.9
    - fitsblender ==0.3.5  # [py2k]
    - fitsblender ==0.3.6  # [py3k]
    - fitsverify ==4.18
    - ginga ==2.7.2  # [py2k]
    - ginga ==3.1.0  # [py3k]
    - glue-core ==0.15.6
    - glue-vispy-viewers ==0.12.2  # [py2k]
    - glueviz ==1.0.0  # [py2k]
    - gwcs ==0.8.0  # [py2k]
    - gwcs ==0.14.0  # [py3k]
    - hstcal ==2.5.0
    - htc_utils ==0.1.0
    - hypothesis ==4.54.2  # [py2k]
    - hypothesis ==6.0.2  # [py3k]
    - imexam ==0.8.1  # [py2k]
    - imexam ==0.9.1  # [py3k]
    - jdat_notebooks ==0.2.0  # [py3k]
    - jeepney ==0.5.0  # [py3k and osx]
    - jwxml ==0.3.0  # [py3k]
    - keyring ==18.0.0  # [py2k and linux]
    - libgcc ==7.2.0  # [linux]
    - libgcc ==4.8.5  # [osx]
    - lockfile ==0.12.2  # [py3k]
    - mdp ==3.5  # [py2k]
    - mosviz ==0.1.1  # [py2k]
    - mosviz ==0.3.0  # [py3k]
    - mpl-scatter-density ==0.6  # [py2k]
    - mpl-scatter-density ==0.7  # [py3k]
    - nictools ==1.1.4  # [py2k]
    - nictools ==1.1.5  # [py3k]
    - parsley ==1.3
    - photutils ==0.4.1  # [py2k]
    - photutils ==1.0.1  # [py3k]
    - plotly ==4.14.3
    - py-expression-eval ==0.3.4  # [py2k]
    - poppy ==0.9.1  # [py3k]
    - pyds9 ==1.9.0.dev145+gc1bf67a  # [py2k]
    - pyds9 ==1.9.0.dev185+gf1f0aae  # [py3k]
    - pyfftw ==0.9.2
    - pyobjc-core ==3.1.1  # [osx]
    - pyobjc-framework-cocoa ==3.1.1  # [osx]
    - pyobjc-framework-quartz ==3.1.1  # [osx]
    - pyopengl ==3.1.1a1  # [py2k]
    - pypdf2 ==1.26.0  # [py3k]
    - pyqtgraph ==0.11.0
    - pysiaf ==0.10.0  # [py3k]
    - pysynphot ==0.9.12  # [py2k]
    - pysynphot ==1.0.0  # [py3k]
    - pytest-arraydiff ==0.3
    - pytest-astropy ==0.8.0
    - pytest-astropy-header ==0.1.2
    - pytest-doctestplus ==0.5.0  # [py2k]
    - pytest-doctestplus ==0.9.0  # [py3k]
    - pytest-openfiles ==0.4.0  # [py2k]
    - pytest-openfiles ==0.5.0  # [py3k]
    - pytest-remotedata ==0.3.2
    - radio-beam ==0.2
    - reftools ==1.7.4  # [py2k]
    - reftools ==2.0.0  # [py3k]
    - retrying ==1.3.3
    - secretstorage ==2.3.1  # [py2k and linux]
    - semantic_version ==2.6.0  # [py2k]
    - semantic_version ==2.8.4  # [py3k]
    - setuptools_scm ==5.0.1  # [py3k]
    - sextractor ==2.19.5
    - spectral-cube ==0.4.3
    - specutils ==0.2.2  # [py2k]
    - specutils ==1.1  # [py3k]
    - specviz ==0.5.0  # [py2k]
    - specviz ==0.7.0  # [py3k]
    - spherical-geometry ==1.2.10  # [py2k]
    - spherical-geometry ==1.2.18  # [py3k]
    - stginga ==0.3  # [py2k]
    - stginga ==1.2.0  # [py3k]
    - stistools ==1.3.0
    - stregion ==1.1.4  # [py2k]
    - stregion ==1.1.6  # [py3k]
    # These 3 meta-packages are redundant, but keep them by default just so
    # that it's easier to see which versions we're using:
    - stsci ==3.1.0  # [py2k]
    - stsci ==3.2.0  # [py3k]
    - stsci-data-analysis ==2.2.0  # [py2k]
    - stsci-data-analysis ==4.0.0  # [py3k]
    - stsci-hst ==3.1.1
    - stsci.convolve ==2.2.2
    - stsci.distutils ==0.3.8
    - stsci.image ==2.3.1  # [py2k]
    - stsci.image ==2.3.3  # [py3k]
    - stsci.imagemanip ==1.1.4
    - stsci.imagestats ==1.4.3  # [py2k]
    - stsci.imagestats ==1.6.2  # [py3k]
    - stsci.ndimage ==0.10.1
    - stsci.skypac ==0.9.15  # [py2k]
    - stsci.skypac ==1.0.5  # [py3k]
    - stsci.stimage ==0.2.2  # [py2k]
    - stsci.stimage ==0.2.4  # [py3k]
    - stsci.tools ==3.6.0
    - stwcs ==1.3.2  # [py2k]
    - stwcs ==1.6.1  # [py3k]
    - tweakwcs ==0.7.0  # [py3k]
    - wcstools ==3.9.5
    - webbpsf ==0.9.0  # [py3k]
    - webbpsf-data ==0.9.0  # [py3k]
    - wfc3tools ==1.3.5
    - wfpc2tools ==1.0.4
    # -----
    - ephem ==3.7.7.0  # [py2k]
    - ephem ==3.7.7.1  # [py3k]
    - sphinx_rtd_theme ==0.4.3
    # -----
    # Omitting the "gemini" version allows that to be updated independently
    # and this meta-package to be re-used for different operational tags;
    # the actual tag(/date) version to use is specified at install time.
    # - gemini  # leave out to allow base install without our internal builds

