# This meta-package (roughly equivalent to "anaconda iraf-all pyraf stsci") is
# used for configuration control of the base Anaconda & AstroConda package
# versions used internally at Gemini.
#
# - The "gemini-anaconda" package is almost the same as "anaconda" in the root
#   environment, but potentially with minor edits to allow for specific version
#   requirements or conflicts.
# - The "stsci" meta-package and its sub-packages do not pin dependencies to
#   specific versions, so are recreated here; likewise for iraf-all.
# - Using OS-specific "builds" allows for unavailability of particular packages
#   on a certain OS or Python version.

about:
    license: BSD
    summary: Base AstroConda installation for internal use at Gemini
build:
    number: '0'
package:
    name: gemini-base
    version: 2.1
requirements:
    # There are no build requirements since we don't maintain the packages
    # (and if we were to, it wouldn't be via this particular meta-package).
    build:
    - python  # needs to be in the recipe for Python-specific builds
    run:
    - python
    - gemini-anaconda ==5.2.0.g0
    # -----
    - iraf ==2.16.UR    # [py2k]
    - iraf ==2.16.UR.1  # [py3k]
    - iraf-x11 ==2.0
    - iraf.adccdrom ==2013_01_02
    - iraf.axe ==2.6.2
    - iraf.cfh12k ==2013_01_02
    - iraf.cirred ==2007_12_13
    - iraf.ctio ==2010_11_18
    - iraf.cutoutpkg ==2001_04_05
    - iraf.deitab ==2013_01_02
    - iraf.esowfi ==2013_01_02
    - iraf.finder ==2.2
    - iraf.fitsutil ==2011_02_22
    - iraf.gmisc ==2010_11_18
    - iraf.guiapps ==2010_11_18
    - iraf.mem0 ==2013_01_02
    - iraf.mscdb ==2011_02_28
    - iraf.mscred ==5.04
    - iraf.mtools ==2013_01_02
    - iraf.nfextern ==2013_01_02
    - iraf.rvsao ==2.7.8
    - iraf.sqiid ==2013_01_02
    - iraf.stecf ==3.17
    - iraf.stsdas ==3.18.3
    - iraf.tables ==3.18.3
    - iraf.ucsclris ==2013_01_02
    - iraf.upsqiid ==2013_01_02
    - iraf.xdimsum ==2010_11_18
    - iraf.xray ==2.5.y2k
    # -----
    - pyraf ==2.1.11.JT
    - pyraf.kepler ==2.6.3  # [py2k]
    # -----
    - acstools ==2.0.10
    - asdf ==1.3.3  # [py2k]
    - asdf ==2.0.1  # [py3k]
    - asteval ==0.9.11
    - astroimtools ==0.1.1
    - atlas-generic ==3.10.2  # [linux]
    - calcos ==3.3.4
    - cfitsio ==3.440
    - costools ==1.2.1
    - crds ==7.2.2
    - cubeviz ==0.0.2
    - d2to1 ==0.2.12
    - dbus-glib ==0.108  # [linux]
    - dbus-python ==1.2.4  # [linux]
    - dill ==0.2.7.1
    - docopt ==0.6.2
    - drizzlepac ==2.2.3
    - ds9 ==7.1
    - fftw ==3.3.4
    - fitsblender ==0.3.2
    - fitsverify ==4.18
    - future ==0.16.0  # [py2k]
    - ginga ==2.7.0
    - glue-core ==0.12.0
    - glue-ginga ==0.2
    - glue-vispy-viewers ==0.9
    - glueviz ==0.12.0
    - gwcs ==0.8.0  # [py2k]
    - gwcs ==0.9.1  # [py3k]
    - hstcal ==2.0.0
    - htc_utils ==0.1.0
    - imexam ==0.8.0
    - keyring ==12.2.1
    - libgcc ==4.8.5  # [osx]
    - lockfile ==0.12.2
    - mdp ==3.5  # [py2k]
    - mosviz ==0.1.1
    - nictools ==1.1.3
    - parsley ==1.3
    - photutils ==0.4
    - pkg-config ==0.29.2
    - pkgconfig ==1.3.1
    - plotly ==2.7.0
    - purge_path ==1.2.0
    - py-expression-eval ==0.3.4
    - pyds9 ==1.9.0.dev61+g3761d7a
    - pyfftw ==0.9.2
    - pyobjc-core ==3.1.1  # [osx]
    - pyobjc-framework-cocoa ==3.1.1  # [osx]
    - pyobjc-framework-quartz ==3.1.1  # [osx]
    - pyopengl ==3.1.1a1
    - pyqtgraph ==0.10.0
    - pyregion ==2.0
    - pysynphot ==0.9.12
    - radio-beam ==0.2
    - reftools ==1.7.4
    - secretstorage ==2.3.1  # [linux]
    - semantic_version ==2.6.0
    - spectral-cube ==0.4.1
    - specutils ==0.2.2
    - specviz ==0.5.0
    - spherical-geometry ==1.2.2
    - sphinx_rtd_theme >=0.3.0
    - stginga ==0.3
    - stistools ==1.1
    # - stsci ==3.0.2  # this package effectively replaces these meta-pkgs
    # - stsci-data-analysis ==2.1.1
    # - stsci-hst ==3.0.2
    - stsci.convolve ==2.2.2
    - stsci.distutils ==0.3.8
    - stsci.image ==2.3.0
    - stsci.imagemanip ==1.1.2
    - stsci.imagestats ==1.4.2
    - stsci.ndimage ==0.10.1
    - stsci.numdisplay ==1.6.1
    - stsci.skypac ==0.9.12
    - stsci.sphere ==0.2
    - stsci.sphinxext ==1.2.2
    - stsci.stimage ==0.2.2
    - stsci.tools ==3.4.12
    - stwcs ==1.3.2  # [py2k]
    - stwcs ==1.4.0  # [py3k]
    - wcstools ==3.9.5
    - wfc3tools ==1.3.4
    - wfpc2tools ==1.0.3
    # -----
    - sextractor ==2.19.5
    - ephem ==3.7.6.0
    - astroquery ==0.3.7
    # -----
    # Omitting the "gemini" version allows that to be updated independently
    # and this meta-package to be re-used for different operational tags;
    # the actual tag(/date) version to use is specified at install time.
    # - gemini  # leave out to allow base install without our internal builds

