# This meta-package (equivalent to "anaconda iraf-all pyraf stsci") is used
# for configuration control of the base Anaconda & AstroConda package versions
# used internally at Gemini.
#
# - Currently the standard "anaconda" package is used to pull in the
#   packages from the root environment, but those may instead need specifying
#   individually if we have to override any versions and/or there are version
#   conflicts with STScI's AstroConda package dependencies.
# - The "stsci" meta-package and its sub-packages do not pin dependencies to
#   specific versions, so are recreated here; likewise for iraf-all.
# - This could perhaps be a "noarch" package, but OS-specific "builds" allow
#   for unavailability of particular packages on some OS in future.

about:
    license: BSD
    summary: Base AstroConda installation for internal use at Gemini
build:
    number: '0'
package:
    name: gemini-base
    version: 0.2
requirements:
    # There are no build requirements since we don't maintain the packages
    # (and if we were to, it wouldn't be via this particular meta-package).
    run:
    - anaconda ==4.2.0
    # -----
    - iraf ==2.16.UR
    - iraf-x11 ==2.0
    - iraf.fitsutil ==2011_02_22
    - iraf.tables ==3.17
    - iraf.stsdas ==3.17
    - iraf.stecf ==3.17
    # - iraf.kepler ==2.6.2
    - iraf.cirred ==2007_12_13
    - iraf.ctio ==2010_11_18
    - iraf.cutoutpkg ==2001_04_05
    - iraf.finder ==2.2
    - iraf.gmisc ==2010_11_18
    - iraf.guiapps ==2010_11_18
    - iraf.mscdb ==2011_02_28
    - iraf.mscred ==5.04
    - iraf.rvsao ==2.7.8
    - iraf.xdimsum ==2010_11_18
    - iraf.xray ==2.5.y2k
    - iraf.adccdrom ==2013_01_02
    - iraf.cfh12k ==2013_01_02
    - iraf.deitab ==2013_01_02
    - iraf.esowfi ==2013_01_02
    - iraf.mem0 ==2013_01_02
    - iraf.mtools ==2013_01_02
    - iraf.nfextern ==2013_01_02
    # - iraf.optic ==2013_01_02
    - iraf.sqiid ==2013_01_02
    - iraf.ucsclris ==2013_01_02
    - iraf.upsqiid ==2013_01_02
    # -----
    - pyraf ==2.1.11
    # -----
    # - stsci ==1.0.2
    - stsci-hst ==1.0.4
    - stsci-data-analysis ==1.1.1
    - astropy ==1.2.1
    - astroimtools ==0.1.1
    - cfitsio ==3.370
    - d2to1 ==0.2.12
    - ds9 ==7.1  # 7.4-7.5 crash when receiving GMOS data with numdisplay
    - fftw ==3.3.4
    - fitsverify ==4.18
    - htc_utils ==0.1
    - imexam ==0.6.2
    - photutils ==0.3
    - purge_path ==1.0.0
    - pyds9 ==1.8.1  # latest 1.9.0.dev only has a python 3 build on osx
    - pyfftw ==0.9.2
    - stginga ==0.1.2
    - specviz ==0.2.2rc5
    - mosviz ==0.0.1
    - glueviz ==0.9.1
    - asdf ==1.2.1
    - acstools ==2.0.5
    - calcos ==3.1.8
    - costools ==1.2.1
    - crds ==7.0.10
    - drizzlepac ==2.1.6
    - fitsblender ==0.2.6
    - hstcal ==1.1.1
    - nictools ==1.1.3
    - pyregion ==1.1.2
    - pysynphot ==0.9.8.5
    - reftools ==1.7.3
    - stistools ==1.1
    - stsci.convolve ==2.2.0
    - stsci.distutils ==0.3.8
    - stsci.image ==2.2.0
    - stsci.imagemanip ==1.1.2
    - stsci.imagestats ==1.4.1
    - stsci.ndimage ==0.10.1
    - stsci.numdisplay ==1.6.1
    - stsci.sphinxext ==1.2.2
    - stsci.stimage ==0.2.1
    - stsci.skypac ==0.9
    - stsci.sphere ==0.2
    - stsci.tools ==3.4.2.1
    - stwcs ==1.2.4
    - wfpc2tools ==1.0.3
    - wfc3tools ==1.3.4
    # -----
    # Omitting the "gemini" version allows that to be updated independently
    # and this meta-package to be re-used for different operational tags;
    # the actual tag(/date) version to use is specified at install time.
    # - gemini  # leave out to allow base install without our internal builds

