{% set version = TAG + '_' + DATE %}

about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: The "gemaux" Python package, for internal Gemini operations
build:
    binary_relocation: True
    number: '0'
    script: python setup.py install
package:
    name: gemini.gemaux_python
    version: {{ version }}
source:
    fn: gemaux_python-{{ version }}.tar.gz
    url: http://astroconda-source:4440/gemaux_python-{{ version }}.tar.gz
requirements:
    # Most of the dependencies besides python are not actually needed to
    # "build" gemaux_python, but including them here ensures that they get
    # built and therefore that the package is installable.
    build:
    - python x.x                # syntax needed to force 2.7 builds...
    - astropy >=1.0.1
    - gemini.gemini_python =={{ version }}  # require same tag & checkout day?
    - matplotlib >=1.4.2
    - numpy >=1.9.1
    - pyds9 >=1.8.1
    - pyraf >=2.1.6
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - stsci.numdisplay >=1.6
    run:
    - python >=2.7,<3.0
    - astropy >=1.0.1
    - gemini.gemini_python =={{ version }}  # require same tag & checkout day?
    - matplotlib >=1.4.2
    - numpy >=1.9.1
    - pyds9 >=1.8.1
    - pyraf >=2.1.6
    - scipy >=0.15.1
    - scikit-image >=0.10.1
    - stsci.numdisplay >=1.6
    # - klpymisc?? (test_timer.py)

