{% set version = tag + '_' + DATE %}

about:
    home: http://www.gemini.edu/sciops/data-and-results/processing-software
    license: BSD
    summary: Gemini Distortion Correction and Stacking Utility (for GSAOI)
build:
    binary_relocation: True
    number: '0'
    script: python setup.py install
package:
    name: gemini.disco_stu
    version: {{ version }}
source:
    fn: disco_stu-{{ version }}.tar.gz
    url: http://astroconda-source:4440/disco_stu-{{ version }}.tar.gz
requirements:
    build:
    - python x.x                # syntax needed to force 2.7 builds...
    run:
    - python >=2.7              # (uses OrderedDict, argparse)
    - numpy >=1.9               # (version tested, from the manual)
    - scipy >=0.14              # (to match the NumPy requirement)
    - astropy >=1.0             # (from the manual)
    - sextractor >=2.8.6        # (from the manual)

